-- Getting finalist teams between 1965 and 1969

SELECT TEAM.CITY, TEAM.NICKNAME, RANK() OVER (ORDER BY ISNULL(WINS, 0) DESC) AS RANK,
ISNULL(WINS, 0) AS NUM_WINS, ISNULL(RUNNERS_UP, 0) AS NUM_RUNNERS_UP FROM (
    SELECT CHAMPION, COUNT(*) AS WINS
    FROM NBA_FINALS WHERE YEAR BETWEEN 1965 AND 1969 GROUP BY CHAMPION
) AS WINNER FULL OUTER JOIN (
    SELECT VICE_CHAMPION, COUNT(*) AS RUNNERS_UP
FROM NBA_FINALS WHERE YEAR BETWEEN 1965 AND 1969 GROUP BY VICE_CHAMPION
) AS RUNNER_UP ON (WINNER.CHAMPION = RUNNER_UP.VICE_CHAMPION)
JOIN TEAM ON (COALESCE(WINNER.CHAMPION, RUNNER_UP.VICE_CHAMPION) = TEAM.ID)
ORDER BY NUM_WINS DESC, NUM_RUNNERS_UP DESC, TEAM.CITY, TEAM.NICKNAME;
